import type { VehicleProfile } from "@nrs/domain";

export const BUILT_IN_VEHICLE_PROFILES: readonly VehicleProfile[] = [
  {
    id: "builtin-small-hatchback",
    name: "Hatchback nhỏ",
    category: "hatchback",
    lengthM: 3.7,
    widthM: 1.68,
    wheelbaseM: 2.45,
    frontOverhangM: 0.65,
    rearOverhangM: 0.6,
    maxSteerRad: 0.6,
    minTurnRadiusM: 4.1,
    trackWidthM: 1.46,
    dataStatus: "READY",
  },
  {
    id: "builtin-sedan",
    name: "Sedan",
    category: "sedan",
    lengthM: 4.65,
    widthM: 1.82,
    wheelbaseM: 2.72,
    frontOverhangM: 0.95,
    rearOverhangM: 0.98,
    maxSteerRad: 0.56,
    minTurnRadiusM: 5.2,
    trackWidthM: 1.58,
    dataStatus: "READY",
  },
  {
    id: "builtin-suv",
    name: "SUV",
    category: "suv",
    lengthM: 4.7,
    widthM: 1.9,
    wheelbaseM: 2.75,
    frontOverhangM: 0.93,
    rearOverhangM: 1.02,
    maxSteerRad: 0.55,
    minTurnRadiusM: 5.3,
    trackWidthM: 1.64,
    dataStatus: "READY",
  },
  {
    id: "builtin-mpv",
    name: "MPV",
    category: "mpv",
    lengthM: 4.8,
    widthM: 1.85,
    wheelbaseM: 2.84,
    frontOverhangM: 0.95,
    rearOverhangM: 1.01,
    maxSteerRad: 0.54,
    minTurnRadiusM: 5.4,
    trackWidthM: 1.6,
    dataStatus: "READY",
  },
  {
    id: "builtin-pickup",
    name: "Pickup",
    category: "pickup",
    lengthM: 5.3,
    widthM: 1.93,
    wheelbaseM: 3.15,
    frontOverhangM: 0.92,
    rearOverhangM: 1.23,
    maxSteerRad: 0.52,
    minTurnRadiusM: 6.2,
    trackWidthM: 1.67,
    dataStatus: "READY",
  },
];
